import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Core tokens
        primary: '#3525cd',
        'on-primary': '#ffffff',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'primary-container': '#4f46e5',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        'on-primary-container': '#dad7ff',
        'inverse-primary': '#c3c0ff',

        secondary: '#565e74',
        'on-secondary': '#ffffff',
        'secondary-container': '#dae2fd',
        'on-secondary-container': '#5c647a',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',

        tertiary: '#3130c0',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4b4dd8',
        'on-tertiary-container': '#d9d8ff',
        'tertiary-fixed': '#e1e0ff',
        'tertiary-fixed-dim': '#c0c1ff',
        'on-tertiary-fixed': '#07006c',
        'on-tertiary-fixed-variant': '#2f2ebe',

        error: '#EF4444',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',

        // Surfaces
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        surface: '#f8f9ff',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'on-surface-variant': '#464555',
        'surface-main': '#FFFFFF',
        'surface-muted': '#F8FAFC',
        'surface-sidebar': '#0F172A',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-tint': '#4d44e3',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',

        // Utility
        outline: '#777587',
        'outline-variant': '#c7c4d8',
        'border-subtle': '#E2E8F0',
        'text-primary': '#0F172A',
        'text-secondary': '#475569',
        success: '#10B981',
        warning: '#F59E0B',
      },
      fontFamily: {
        sans: ['Poppins', 'system-ui', 'sans-serif'],
        'body-medium': ['Poppins'],
        'body-base': ['Poppins'],
        'headline-sm': ['Poppins'],
        'headline-md': ['Poppins'],
        'label-sm': ['Poppins'],
        'display-lg': ['Poppins'],
        'mono-code': ['"JetBrains Mono"', 'Consolas', 'monospace'],
      },
      fontSize: {
        'body-medium': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'mono-code': ['13px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
