AI_MODEL = 'gpt-4o'

MCP_TIMEOUT_MS = 30_000
MCP_PROTOCOL_VERSION = '2024-11-05'
PLAYWRIGHT_BROWSER = 'chromium'

PIPELINE_KILL_TIMEOUT_MS = 4 * 60_000  # outer backstop; per-test pytest-timeout is 30s
MAX_PLANNER_ITERATIONS = 20
MAX_GENERATOR_ITERATIONS = 20
PLANNER_NUDGE_THRESHOLD = 0.75
GENERATOR_NUDGE_THRESHOLD = 0.7
GENERATOR_FINAL_WARNING_THRESHOLD = 0.87

EXCLUDED_SPEC_FILES = frozenset(['conftest.py', 'helpers.py'])
MIN_SLUG_WORD_LENGTH = 3

ERROR_TRUNCATE_LENGTH = 400

SESSION_EXPIRY_SECONDS = 60 * 60 * 24
LOGIN_TIMEOUT_MS = 30_000
LOGIN_PATH = '/login'
