# Generated by Django 5.2.1 on 2026-06-17 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.TextField()),
                ('deleted_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('base_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.TextField()),
                ('login_email', models.TextField(default='')),
                ('login_password', models.TextField(default='')),
                ('deleted_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'environments',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('started_at', models.TextField()),
                ('completed_at', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('pass_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('report_dir', models.TextField(blank=True, null=True)),
                ('deleted_at', models.TextField(blank=True, null=True)),
                ('environment', models.ForeignKey(db_column='environment_id', on_delete=django.db.models.deletion.RESTRICT, related_name='executions', to='core.environment')),
            ],
            options={
                'db_table': 'executions',
            },
        ),
        migrations.CreateModel(
            name='ExecutionStep',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('step_name', models.TextField()),
                ('status', models.TextField()),
                ('log', models.TextField(default='')),
                ('started_at', models.TextField()),
                ('completed_at', models.TextField(blank=True, null=True)),
                ('deleted_at', models.TextField(blank=True, null=True)),
                ('execution', models.ForeignKey(db_column='execution_id', on_delete=django.db.models.deletion.RESTRICT, related_name='steps', to='core.execution')),
            ],
            options={
                'db_table': 'execution_steps',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('prompt', models.TextField(default='')),
                ('status', models.TextField(default='active')),
                ('environment_ids', models.TextField(default='[]')),
                ('created_at', models.TextField()),
                ('deleted_at', models.TextField(blank=True, null=True)),
                ('collection', models.ForeignKey(db_column='collection_id', on_delete=django.db.models.deletion.RESTRICT, related_name='tests', to='core.collection')),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='test',
            field=models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.RESTRICT, related_name='executions', to='core.test'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'deleted'])), name='tests_status_check'),
        ),
    ]
