# Generated by Django 5.2.15 on 2026-07-28 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_executionstep_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('storage_state', models.TextField(default='')),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('deleted_at', models.TextField(blank=True, null=True)),
                ('environment', models.ForeignKey(blank=True, db_column='environment_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='core.environment')),
            ],
            options={
                'db_table': 'auth_sessions',
            },
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('results_json', models.TextField(default='')),
                ('step_failure_json', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('deleted_at', models.TextField(blank=True, null=True)),
                ('execution', models.ForeignKey(db_column='execution_id', on_delete=django.db.models.deletion.RESTRICT, related_name='result', to='core.execution')),
            ],
            options={
                'db_table': 'execution_results',
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('plan_md', models.TextField(default='')),
                ('plan_snapshots', models.TextField(default='{}')),
                ('plan_prompt', models.TextField(default='')),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('deleted_at', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.RESTRICT, related_name='plan', to='core.test')),
            ],
            options={
                'db_table': 'test_plans',
            },
        ),
        migrations.CreateModel(
            name='TestSpec',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('content', models.TextField(default='')),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('deleted_at', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.RESTRICT, related_name='specs', to='core.test')),
            ],
            options={
                'db_table': 'test_specs',
            },
        ),
    ]
